#ifndef PAGERECORDLIST_H
#define PAGERECORDLIST_H

#include <QWidget>
#include "page.h"
#include "userprofile.h"

namespace Ui {
class PageRecordList;
}

/*
 * PageRecordList Class:
 * - Displays a list of records associated with a specific user profile.
 * - Allows the user to view, add, or edit records for the selected profile.
 */
class PageRecordList : public Page
{
    Q_OBJECT

public:
    /*
     * Constructor: Initializes the record list page
     * @param profileIdx: Index of the user profile whose records are displayed
     * @param mainWindow: Pointer to the MainWindow for access to shared resources
     * @param parentMenu: Pointer to the parent page for back navigation
     * @param parent: Optional QWidget parent (default nullptr)
     */
    explicit PageRecordList(int profileIdx, MainWindow *mainWindow, Page *parentMenu, QWidget *parent = nullptr);

    ~PageRecordList();

    /*
     * update:
     * - Refreshes the list of records displayed on the page.
     * - Ensures the UI reflects any changes to the records.
     */
    void update();

private:
    Ui::PageRecordList *ui;  // Pointer to the UI components generated by Qt Designer

    int profileIdx;          // Index of the user profile being displayed
    UserProfile *profile;    // Pointer to the selected user profile

    /*
     * viewRecord:
     * - Opens the page to display details of a specific record.
     * @param recordId: ID of the record to view
     */
    void viewRecord(int recordId);

    /*
     * newRecord:
     * - Creates a new record for the current profile.
     * - Navigates to the page for taking a new reading.
     */
    void newRecord();

    /*
     * editProfile:
     * - Opens the profile edit page to modify user details.
     */
    void editProfile();
};

#endif // PAGERECORDLIST_H
